export type IngredientCategory =
  | "flours"
  | "sugars"
  | "dairyEggs"
  | "fatsOils"
  | "nutsSeeds"
  | "fruits"
  | "vegetables"
  | "chocolate"
  | "grains"
  | "liquids"
  | "leavenersSalt"
  | "spreads"
  | "other";

export type ReferenceVolume =
  | "1 cup"
  | "1/2 cup"
  | "1/4 cup"
  | "1/3 cup"
  | "2 cups"
  | "4 cups"
  | "1 tablespoon"
  | "2 tablespoons"
  | "1 teaspoon"
  | "1/2 teaspoon";

export const REFERENCE_VOLUME_ML: Record<ReferenceVolume, number> = {
  "1 cup": 236.5882365,
  "1/2 cup": 118.29411825,
  "1/4 cup": 59.147059125,
  "1/3 cup": 78.8627455,
  "2 cups": 473.176473,
  "4 cups": 946.352946,
  "1 tablespoon": 14.786764781,
  "2 tablespoons": 29.573529563,
  "1 teaspoon": 4.928921594,
  "1/2 teaspoon": 2.464460797,
};

export interface IngredientDensity {
  key: string;
  category: IngredientCategory;
  grams: number;
  reference: ReferenceVolume;
  varies?: boolean;
}

export interface CountItem {
  key: string;
  gramsPerUnit: number;
  varies?: boolean;
}

export const INGREDIENT_DENSITIES: IngredientDensity[] = [
  { key: "zeroZeroFlour", category: "flours", grams: 116, reference: "1 cup" },
  {
    key: "allPurposeFlour",
    category: "flours",
    grams: 120,
    reference: "1 cup",
  },
  { key: "almondFlour", category: "flours", grams: 96, reference: "1 cup" },
  { key: "almondMeal", category: "flours", grams: 84, reference: "1 cup" },
  { key: "amaranthFlour", category: "flours", grams: 103, reference: "1 cup" },
  { key: "barleyFlour", category: "flours", grams: 85, reference: "1 cup" },
  { key: "breadFlour", category: "flours", grams: 136, reference: "1 cup" },
  { key: "brownRiceFlour", category: "flours", grams: 128, reference: "1 cup" },
  { key: "buckwheatFlour", category: "flours", grams: 120, reference: "1 cup" },
  { key: "cakeFlour", category: "flours", grams: 120, reference: "1 cup" },
  { key: "chickpeaFlour", category: "flours", grams: 85, reference: "1 cup" },
  { key: "coconutFlour", category: "flours", grams: 128, reference: "1 cup" },
  { key: "cornstarch", category: "flours", grams: 28, reference: "1/4 cup" },
  { key: "durumFlour", category: "flours", grams: 124, reference: "1 cup" },
  {
    key: "firstClearFlour",
    category: "flours",
    grams: 106,
    reference: "1 cup",
  },
  {
    key: "glutenFreeAllPurposeFlour",
    category: "flours",
    grams: 156,
    reference: "1 cup",
  },
  {
    key: "glutinousRiceFlour",
    category: "flours",
    grams: 120,
    reference: "1 cup",
  },
  { key: "hazelnutFlour", category: "flours", grams: 89, reference: "1 cup" },
  {
    key: "highGlutenFlour",
    category: "flours",
    grams: 120,
    reference: "1 cup",
  },
  { key: "masaHarina", category: "flours", grams: 93, reference: "1 cup" },
  { key: "oatFlour", category: "flours", grams: 92, reference: "1 cup" },
  { key: "pastryFlour", category: "flours", grams: 106, reference: "1 cup" },
  { key: "pecanMeal", category: "flours", grams: 80, reference: "1 cup" },
  { key: "potatoFlour", category: "flours", grams: 46, reference: "1/4 cup" },
  { key: "potatoStarch", category: "flours", grams: 152, reference: "1 cup" },
  {
    key: "pumpernickelFlour",
    category: "flours",
    grams: 106,
    reference: "1 cup",
  },
  { key: "quinoaFlour", category: "flours", grams: 110, reference: "1 cup" },
  { key: "riceFlourWhite", category: "flours", grams: 142, reference: "1 cup" },
  { key: "ryeFlourMedium", category: "flours", grams: 106, reference: "1 cup" },
  {
    key: "selfRisingFlour",
    category: "flours",
    grams: 113,
    reference: "1 cup",
  },
  { key: "semolinaFlour", category: "flours", grams: 163, reference: "1 cup" },
  { key: "sorghumFlour", category: "flours", grams: 138, reference: "1 cup" },
  { key: "soyFlour", category: "flours", grams: 35, reference: "1/4 cup" },
  { key: "speltFlour", category: "flours", grams: 99, reference: "1 cup" },
  {
    key: "sproutedWheatFlour",
    category: "flours",
    grams: 113,
    reference: "1 cup",
  },
  { key: "tapiocaStarch", category: "flours", grams: 113, reference: "1 cup" },
  { key: "teffFlour", category: "flours", grams: 135, reference: "1 cup" },
  {
    key: "vitalWheatGluten",
    category: "flours",
    grams: 18,
    reference: "2 tablespoons",
  },
  {
    key: "wholeWheatFlour",
    category: "flours",
    grams: 113,
    reference: "1 cup",
  },
  {
    key: "wholeWheatPastryFlour",
    category: "flours",
    grams: 96,
    reference: "1 cup",
  },
  { key: "whiteRyeFlour", category: "flours", grams: 106, reference: "1 cup" },
  {
    key: "whiteWholeWheatFlour",
    category: "flours",
    grams: 113,
    reference: "1 cup",
  },

  { key: "superfineSugar", category: "sugars", grams: 190, reference: "1 cup" },
  {
    key: "brownSugarPacked",
    category: "sugars",
    grams: 213,
    reference: "1 cup",
  },
  { key: "coconutSugar", category: "sugars", grams: 77, reference: "1/2 cup" },
  {
    key: "confectionersSugar",
    category: "sugars",
    grams: 227,
    reference: "2 cups",
  },
  { key: "cinnamonSugar", category: "sugars", grams: 50, reference: "1/4 cup" },
  { key: "demeraraSugar", category: "sugars", grams: 220, reference: "1 cup" },
  {
    key: "granulatedSugar",
    category: "sugars",
    grams: 198,
    reference: "1 cup",
  },
  { key: "mapleSugar", category: "sugars", grams: 78, reference: "1/2 cup" },
  { key: "pearlSugar", category: "sugars", grams: 49, reference: "1/4 cup" },
  { key: "turbinadoSugar", category: "sugars", grams: 180, reference: "1 cup" },

  { key: "buttermilk", category: "dairyEggs", grams: 245, reference: "1 cup" },
  {
    key: "buttermilkPowder",
    category: "dairyEggs",
    grams: 18,
    reference: "2 tablespoons",
  },
  { key: "cheeseFeta", category: "dairyEggs", grams: 57, reference: "1/2 cup" },
  {
    key: "cheeseGrated",
    category: "dairyEggs",
    grams: 113,
    reference: "1 cup",
  },
  {
    key: "cheeseParmesanGrated",
    category: "dairyEggs",
    grams: 50,
    reference: "1/2 cup",
  },
  {
    key: "cheeseRicotta",
    category: "dairyEggs",
    grams: 246,
    reference: "1 cup",
  },
  { key: "cream", category: "dairyEggs", grams: 238, reference: "1 cup" },
  { key: "creamCheese", category: "dairyEggs", grams: 232, reference: "1 cup" },
  {
    key: "cremeFraiche",
    category: "dairyEggs",
    grams: 124,
    reference: "1/2 cup",
  },
  {
    key: "driedNonfatMilk",
    category: "dairyEggs",
    grams: 28,
    reference: "1/4 cup",
  },
  {
    key: "driedWholeMilk",
    category: "dairyEggs",
    grams: 50,
    reference: "1/2 cup",
  },
  {
    key: "eggWhitesDried",
    category: "dairyEggs",
    grams: 11,
    reference: "2 tablespoons",
  },
  { key: "mascarpone", category: "dairyEggs", grams: 227, reference: "1 cup" },
  {
    key: "milkEvaporated",
    category: "dairyEggs",
    grams: 113,
    reference: "1/2 cup",
  },
  { key: "milk", category: "dairyEggs", grams: 249, reference: "1 cup" },
  {
    key: "quesoFresco",
    category: "dairyEggs",
    grams: 57,
    reference: "1/2 cup",
  },
  { key: "sourCream", category: "dairyEggs", grams: 230, reference: "1 cup" },
  { key: "yogurt", category: "dairyEggs", grams: 245, reference: "1 cup" },

  { key: "butter", category: "fatsOils", grams: 113, reference: "1/2 cup" },
  { key: "coconutOil", category: "fatsOils", grams: 113, reference: "1/2 cup" },
  { key: "ghee", category: "fatsOils", grams: 44, reference: "1/4 cup" },
  { key: "lard", category: "fatsOils", grams: 113, reference: "1/2 cup" },
  { key: "oliveOil", category: "fatsOils", grams: 50, reference: "1/4 cup" },
  {
    key: "palmShortening",
    category: "fatsOils",
    grams: 45,
    reference: "1/4 cup",
  },
  { key: "vegetableOil", category: "fatsOils", grams: 198, reference: "1 cup" },
  {
    key: "vegetableShortening",
    category: "fatsOils",
    grams: 46,
    reference: "1/4 cup",
  },

  {
    key: "almondsSliced",
    category: "nutsSeeds",
    grams: 43,
    reference: "1/2 cup",
  },
  {
    key: "almondsSlivered",
    category: "nutsSeeds",
    grams: 57,
    reference: "1/2 cup",
  },
  {
    key: "almondsWhole",
    category: "nutsSeeds",
    grams: 142,
    reference: "1 cup",
  },
  {
    key: "carawaySeeds",
    category: "nutsSeeds",
    grams: 18,
    reference: "2 tablespoons",
  },
  {
    key: "cashewsChopped",
    category: "nutsSeeds",
    grams: 113,
    reference: "1 cup",
  },
  {
    key: "cashewsWhole",
    category: "nutsSeeds",
    grams: 113,
    reference: "1 cup",
  },
  { key: "chiaSeeds", category: "nutsSeeds", grams: 37, reference: "1/4 cup" },
  {
    key: "coconutSweetenedShredded",
    category: "nutsSeeds",
    grams: 85,
    reference: "1 cup",
  },
  {
    key: "coconutToasted",
    category: "nutsSeeds",
    grams: 85,
    reference: "1 cup",
  },
  {
    key: "coconutDesiccated",
    category: "nutsSeeds",
    grams: 85,
    reference: "1 cup",
  },
  {
    key: "coconutLargeFlakes",
    category: "nutsSeeds",
    grams: 60,
    reference: "1 cup",
  },
  {
    key: "coconutShredded",
    category: "nutsSeeds",
    grams: 53,
    reference: "1 cup",
  },
  { key: "flaxMeal", category: "nutsSeeds", grams: 50, reference: "1/2 cup" },
  { key: "flaxseed", category: "nutsSeeds", grams: 35, reference: "1/4 cup" },
  {
    key: "hazelnutsWhole",
    category: "nutsSeeds",
    grams: 142,
    reference: "1 cup",
  },
  {
    key: "macadamiaNuts",
    category: "nutsSeeds",
    grams: 149,
    reference: "1 cup",
  },
  { key: "peanuts", category: "nutsSeeds", grams: 142, reference: "1 cup" },
  {
    key: "pecansDiced",
    category: "nutsSeeds",
    grams: 57,
    reference: "1/2 cup",
  },
  { key: "pecansWhole", category: "nutsSeeds", grams: 105, reference: "1 cup" },
  { key: "pineNuts", category: "nutsSeeds", grams: 71, reference: "1/2 cup" },
  { key: "pistachios", category: "nutsSeeds", grams: 60, reference: "1/2 cup" },
  {
    key: "poppySeeds",
    category: "nutsSeeds",
    grams: 18,
    reference: "2 tablespoons",
  },
  {
    key: "sesameSeeds",
    category: "nutsSeeds",
    grams: 71,
    reference: "1/2 cup",
  },
  {
    key: "sunflowerSeeds",
    category: "nutsSeeds",
    grams: 35,
    reference: "1/4 cup",
  },
  {
    key: "walnutsChopped",
    category: "nutsSeeds",
    grams: 113,
    reference: "1 cup",
  },
  {
    key: "walnutsWhole",
    category: "nutsSeeds",
    grams: 64,
    reference: "1/2 cup",
  },

  {
    key: "applesDriedDiced",
    category: "fruits",
    grams: 85,
    reference: "1 cup",
  },
  { key: "applesSliced", category: "fruits", grams: 113, reference: "1 cup" },
  { key: "applesauce", category: "fruits", grams: 255, reference: "1 cup" },
  {
    key: "apricotsDried",
    category: "fruits",
    grams: 64,
    reference: "1/2 cup",
  },
  { key: "bananasMashed", category: "fruits", grams: 227, reference: "1 cup" },
  { key: "berriesFrozen", category: "fruits", grams: 142, reference: "1 cup" },
  {
    key: "blueberriesDried",
    category: "fruits",
    grams: 156,
    reference: "1 cup",
  },
  {
    key: "blueberries",
    category: "fruits",
    grams: 155,
    reference: "1 cup",
    varies: true,
  },
  {
    key: "candiedLemonPeel",
    category: "fruits",
    grams: 37,
    reference: "1/4 cup",
  },
  {
    key: "candiedOrangePeel",
    category: "fruits",
    grams: 25,
    reference: "1/4 cup",
  },
  {
    key: "cherriesCandied",
    category: "fruits",
    grams: 50,
    reference: "1/4 cup",
  },
  {
    key: "cherriesDried",
    category: "fruits",
    grams: 71,
    reference: "1/2 cup",
  },
  {
    key: "cherriesFresh",
    category: "fruits",
    grams: 80,
    reference: "1/2 cup",
  },
  {
    key: "cherriesFrozen",
    category: "fruits",
    grams: 113,
    reference: "1 cup",
  },
  {
    key: "cranberriesDried",
    category: "fruits",
    grams: 57,
    reference: "1/2 cup",
  },
  {
    key: "cranberriesFresh",
    category: "fruits",
    grams: 99,
    reference: "1 cup",
  },
  {
    key: "crystallizedGinger",
    category: "fruits",
    grams: 92,
    reference: "1/2 cup",
  },
  { key: "currants", category: "fruits", grams: 142, reference: "1 cup" },
  { key: "datesChopped", category: "fruits", grams: 149, reference: "1 cup" },
  { key: "figsDried", category: "fruits", grams: 149, reference: "1 cup" },
  {
    key: "passionFruitPuree",
    category: "fruits",
    grams: 60,
    reference: "1/3 cup",
  },
  { key: "peaches", category: "fruits", grams: 170, reference: "1 cup" },
  { key: "pears", category: "fruits", grams: 163, reference: "1 cup" },
  {
    key: "pineappleCrushed",
    category: "fruits",
    grams: 256,
    reference: "1 cup",
  },
  {
    key: "pineappleDried",
    category: "fruits",
    grams: 71,
    reference: "1/2 cup",
  },
  {
    key: "pineappleDiced",
    category: "fruits",
    grams: 170,
    reference: "1 cup",
  },
  { key: "raisinsLoose", category: "fruits", grams: 149, reference: "1 cup" },
  {
    key: "raisinsPacked",
    category: "fruits",
    grams: 85,
    reference: "1/2 cup",
  },
  { key: "raspberries", category: "fruits", grams: 120, reference: "1 cup" },
  {
    key: "rhubarb",
    category: "fruits",
    grams: 130,
    reference: "1 cup",
    varies: true,
  },
  { key: "strawberries", category: "fruits", grams: 167, reference: "1 cup" },

  {
    key: "bellPeppers",
    category: "vegetables",
    grams: 142,
    reference: "1 cup",
  },
  {
    key: "carrotsPureed",
    category: "vegetables",
    grams: 128,
    reference: "1/2 cup",
  },
  {
    key: "carrotsDiced",
    category: "vegetables",
    grams: 142,
    reference: "1 cup",
  },
  {
    key: "carrotsGrated",
    category: "vegetables",
    grams: 99,
    reference: "1 cup",
  },
  {
    key: "celeryDiced",
    category: "vegetables",
    grams: 142,
    reference: "1 cup",
  },
  { key: "chives", category: "vegetables", grams: 21, reference: "1/2 cup" },
  {
    key: "cornKernels",
    category: "vegetables",
    grams: 38,
    reference: "1/4 cup",
  },
  {
    key: "garlicMinced",
    category: "vegetables",
    grams: 28,
    reference: "2 tablespoons",
  },
  {
    key: "garlicSliced",
    category: "vegetables",
    grams: 149,
    reference: "1 cup",
  },
  {
    key: "gingerSliced",
    category: "vegetables",
    grams: 57,
    reference: "1/4 cup",
  },
  { key: "leeksDiced", category: "vegetables", grams: 92, reference: "1 cup" },
  {
    key: "mashedPotatoes",
    category: "vegetables",
    grams: 213,
    reference: "1 cup",
  },
  {
    key: "mashedSweetPotatoes",
    category: "vegetables",
    grams: 240,
    reference: "1 cup",
  },
  {
    key: "mushroomsSliced",
    category: "vegetables",
    grams: 78,
    reference: "1 cup",
  },
  {
    key: "olivesSliced",
    category: "vegetables",
    grams: 142,
    reference: "1 cup",
  },
  {
    key: "onionsDiced",
    category: "vegetables",
    grams: 142,
    reference: "1 cup",
  },
  {
    key: "pumpkinPuree",
    category: "vegetables",
    grams: 227,
    reference: "1 cup",
  },
  {
    key: "scallionsSliced",
    category: "vegetables",
    grams: 64,
    reference: "1 cup",
  },
  {
    key: "shallotsSliced",
    category: "vegetables",
    grams: 156,
    reference: "1 cup",
  },
  {
    key: "sundriedTomatoes",
    category: "vegetables",
    grams: 170,
    reference: "1 cup",
  },
  {
    key: "tomatoPaste",
    category: "vegetables",
    grams: 29,
    reference: "2 tablespoons",
  },
  {
    key: "zucchiniShredded",
    category: "vegetables",
    grams: 135,
    reference: "1 cup",
    varies: true,
  },

  { key: "cacaoNibs", category: "chocolate", grams: 120, reference: "1 cup" },
  {
    key: "chocolateChopped",
    category: "chocolate",
    grams: 170,
    reference: "1 cup",
  },
  {
    key: "chocolateChips",
    category: "chocolate",
    grams: 170,
    reference: "1 cup",
  },
  {
    key: "chocolateChunks",
    category: "chocolate",
    grams: 170,
    reference: "1 cup",
  },
  {
    key: "cocoaUnsweetened",
    category: "chocolate",
    grams: 42,
    reference: "1/2 cup",
  },
  {
    key: "miniChocolateChips",
    category: "chocolate",
    grams: 177,
    reference: "1 cup",
  },
  {
    key: "whiteChocolateChips",
    category: "chocolate",
    grams: 170,
    reference: "1 cup",
  },

  { key: "barleyCooked", category: "grains", grams: 215, reference: "1 cup" },
  { key: "barleyPearled", category: "grains", grams: 213, reference: "1 cup" },
  { key: "barleyFlakes", category: "grains", grams: 46, reference: "1/2 cup" },
  { key: "branCereal", category: "grains", grams: 60, reference: "1 cup" },
  {
    key: "brownRiceCooked",
    category: "grains",
    grams: 170,
    reference: "1 cup",
  },
  {
    key: "buckwheatWhole",
    category: "grains",
    grams: 170,
    reference: "1 cup",
  },
  { key: "bulgur", category: "grains", grams: 152, reference: "1 cup" },
  { key: "cornPopped", category: "grains", grams: 21, reference: "4 cups" },
  { key: "cornmealWhole", category: "grains", grams: 138, reference: "1 cup" },
  { key: "cornmealYellow", category: "grains", grams: 156, reference: "1 cup" },
  { key: "crackedWheat", category: "grains", grams: 149, reference: "1 cup" },
  { key: "granola", category: "grains", grams: 113, reference: "1 cup" },
  {
    key: "maltedWheatFlakes",
    category: "grains",
    grams: 64,
    reference: "1/2 cup",
  },
  { key: "millet", category: "grains", grams: 103, reference: "1/2 cup" },
  { key: "oatBran", category: "grains", grams: 53, reference: "1/2 cup" },
  { key: "rolledOats", category: "grains", grams: 89, reference: "1 cup" },
  { key: "oatsPrepared", category: "grains", grams: 147, reference: "1 cup" },
  { key: "polenta", category: "grains", grams: 163, reference: "1 cup" },
  { key: "quinoaCooked", category: "grains", grams: 184, reference: "1 cup" },
  { key: "quinoaWhole", category: "grains", grams: 177, reference: "1 cup" },
  {
    key: "riceLongGrain",
    category: "grains",
    grams: 99,
    reference: "1/2 cup",
  },
  {
    key: "riceShortGrain",
    category: "grains",
    grams: 200,
    reference: "1 cup",
  },
  { key: "ryeChops", category: "grains", grams: 120, reference: "1 cup" },
  { key: "ryeFlakes", category: "grains", grams: 124, reference: "1 cup" },
  {
    key: "steelCutOats",
    category: "grains",
    grams: 70,
    reference: "1/2 cup",
  },
  { key: "wheatBerries", category: "grains", grams: 184, reference: "1 cup" },
  { key: "wheatBran", category: "grains", grams: 32, reference: "1/2 cup" },
  { key: "wheatGerm", category: "grains", grams: 28, reference: "1/4 cup" },

  { key: "agaveSyrup", category: "liquids", grams: 84, reference: "1/4 cup" },
  {
    key: "appleJuiceConcentrate",
    category: "liquids",
    grams: 70,
    reference: "1/4 cup",
  },
  {
    key: "barleyMaltSyrup",
    category: "liquids",
    grams: 42,
    reference: "2 tablespoons",
  },
  {
    key: "blueberryJuice",
    category: "liquids",
    grams: 241,
    reference: "1 cup",
  },
  { key: "boiledCider", category: "liquids", grams: 85, reference: "1/4 cup" },
  {
    key: "cherryConcentrate",
    category: "liquids",
    grams: 42,
    reference: "2 tablespoons",
  },
  { key: "coconutCream", category: "liquids", grams: 284, reference: "1 cup" },
  {
    key: "coconutMilkCanned",
    category: "liquids",
    grams: 241,
    reference: "1 cup",
  },
  {
    key: "coconutMilkEvaporated",
    category: "liquids",
    grams: 242,
    reference: "1 cup",
  },
  {
    key: "creamOfCoconut",
    category: "liquids",
    grams: 142,
    reference: "1/2 cup",
  },
  { key: "cornSyrup", category: "liquids", grams: 312, reference: "1 cup" },
  { key: "honey", category: "liquids", grams: 21, reference: "1 tablespoon" },
  { key: "limeJuice", category: "liquids", grams: 227, reference: "1 cup" },
  {
    key: "lemonJuice",
    category: "liquids",
    grams: 14,
    reference: "1 tablespoon",
  },
  {
    key: "maltSyrup",
    category: "liquids",
    grams: 43,
    reference: "2 tablespoons",
  },
  { key: "mapleSyrup", category: "liquids", grams: 156, reference: "1/2 cup" },
  { key: "molasses", category: "liquids", grams: 85, reference: "1/4 cup" },
  {
    key: "sweetenedCondensedCoconutMilk",
    category: "liquids",
    grams: 288,
    reference: "1 cup",
  },
  {
    key: "sweetenedCondensedMilk",
    category: "liquids",
    grams: 78,
    reference: "1/4 cup",
  },
  { key: "water", category: "liquids", grams: 237, reference: "1 cup" },

  {
    key: "bakingPowder",
    category: "leavenersSalt",
    grams: 4,
    reference: "1 teaspoon",
  },
  {
    key: "bakingSoda",
    category: "leavenersSalt",
    grams: 3,
    reference: "1/2 teaspoon",
  },
  {
    key: "instantYeast",
    category: "leavenersSalt",
    grams: 9,
    reference: "1 tablespoon",
  },
  {
    key: "kosherSaltDiamond",
    category: "leavenersSalt",
    grams: 8,
    reference: "1 tablespoon",
  },
  {
    key: "kosherSaltMorton",
    category: "leavenersSalt",
    grams: 16,
    reference: "1 tablespoon",
  },
  {
    key: "tableSalt",
    category: "leavenersSalt",
    grams: 18,
    reference: "1 tablespoon",
  },

  { key: "almondButter", category: "spreads", grams: 68, reference: "1/4 cup" },
  { key: "almondPaste", category: "spreads", grams: 259, reference: "1 cup" },
  {
    key: "basilPesto",
    category: "spreads",
    grams: 28,
    reference: "2 tablespoons",
  },
  { key: "cookieButter", category: "spreads", grams: 72, reference: "1/4 cup" },
  { key: "guavaPaste", category: "spreads", grams: 100, reference: "1/4 cup" },
  {
    key: "hazelnutPralinePaste",
    category: "spreads",
    grams: 156,
    reference: "1/2 cup",
  },
  {
    key: "hazelnutSpread",
    category: "spreads",
    grams: 160,
    reference: "1/2 cup",
  },
  { key: "jamPreserves", category: "spreads", grams: 85, reference: "1/4 cup" },
  { key: "lemonCurd", category: "spreads", grams: 113, reference: "1/2 cup" },
  { key: "marzipan", category: "spreads", grams: 290, reference: "1 cup" },
  { key: "mayonnaise", category: "spreads", grams: 113, reference: "1/2 cup" },
  {
    key: "marshmallowSpreadHomemade",
    category: "spreads",
    grams: 72,
    reference: "1 cup",
  },
  {
    key: "marshmallowSpread",
    category: "spreads",
    grams: 123,
    reference: "1 cup",
  },
  {
    key: "peanutButter",
    category: "spreads",
    grams: 135,
    reference: "1/2 cup",
  },
  {
    key: "pistachioPaste",
    category: "spreads",
    grams: 78,
    reference: "1/4 cup",
  },
  { key: "tahini", category: "spreads", grams: 128, reference: "1/2 cup" },

  {
    key: "breadCrumbsDried",
    category: "other",
    grams: 28,
    reference: "1/4 cup",
  },
  {
    key: "breadCrumbsFresh",
    category: "other",
    grams: 21,
    reference: "1/4 cup",
  },
  { key: "panko", category: "other", grams: 50, reference: "1 cup" },
  { key: "caramel", category: "other", grams: 142, reference: "1/2 cup" },
  { key: "caramelBits", category: "other", grams: 156, reference: "1 cup" },
  { key: "cookieCrumbs", category: "other", grams: 85, reference: "1 cup" },
  {
    key: "driedPotatoFlakes",
    category: "other",
    grams: 43,
    reference: "1/2 cup",
  },
  {
    key: "espressoPowder",
    category: "other",
    grams: 7,
    reference: "1 tablespoon",
  },
  {
    key: "grahamCrackerCrumbs",
    category: "other",
    grams: 100,
    reference: "1 cup",
  },
  {
    key: "maltedMilkPowder",
    category: "other",
    grams: 35,
    reference: "1/4 cup",
  },
  { key: "marshmallowsMini", category: "other", grams: 43, reference: "1 cup" },
  {
    key: "meringuePowder",
    category: "other",
    grams: 43,
    reference: "1/4 cup",
  },
  {
    key: "coconutMilkPowder",
    category: "other",
    grams: 57,
    reference: "1/2 cup",
  },
  { key: "pizzaSauce", category: "other", grams: 57, reference: "1/4 cup" },
  {
    key: "sourdoughStarter",
    category: "other",
    grams: 234,
    reference: "1 cup",
    varies: true,
  },
  {
    key: "tapiocaQuickCooking",
    category: "other",
    grams: 21,
    reference: "2 tablespoons",
  },
  { key: "toffeeChunks", category: "other", grams: 156, reference: "1 cup" },
  {
    key: "vanillaExtract",
    category: "other",
    grams: 14,
    reference: "1 tablespoon",
  },
];

export const COUNT_ITEMS: CountItem[] = [
  { key: "egg", gramsPerUnit: 50 },
  { key: "eggWhite", gramsPerUnit: 33, varies: true },
  { key: "eggYolk", gramsPerUnit: 14 },
  { key: "butterStick", gramsPerUnit: 113 },
  { key: "garlicClove", gramsPerUnit: 3, varies: true },
  { key: "garlicHead", gramsPerUnit: 113, varies: true },
  { key: "appleMedium", gramsPerUnit: 182, varies: true },
  { key: "avocadoMedium", gramsPerUnit: 150, varies: true },
  { key: "bananaMedium", gramsPerUnit: 118, varies: true },
  { key: "bellPepperMedium", gramsPerUnit: 119, varies: true },
  { key: "breadSlice", gramsPerUnit: 33, varies: true },
  { key: "carrotMedium", gramsPerUnit: 61, varies: true },
  { key: "lemonMedium", gramsPerUnit: 58, varies: true },
  { key: "limeMedium", gramsPerUnit: 67, varies: true },
  { key: "onionMedium", gramsPerUnit: 110, varies: true },
  { key: "potatoMedium", gramsPerUnit: 213, varies: true },
  { key: "tomatoMedium", gramsPerUnit: 123, varies: true },
  { key: "zucchiniMedium", gramsPerUnit: 196, varies: true },
];
