version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
commands:
  install-dependencies:
    steps:
      # - restore_cache:
      #     keys:
      #       - dependency-cache-v2-{{ checksum "package-lock.json" }}
      #       - dependency-cache-v2-
      - run:
          name: install-deps
          command: "npm ci"
      # - save_cache:
      #     key: dependency-cache-v2-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules
jobs:
  build_and_test:
    resource_class: large
    docker:
      - image: cimg/node:24.13
        environment:
          RS_TEST_DB_USERNAME: chefbook
          RS_TEST_DB_PASSWORD: admin
          RS_TEST_DB_DATABASE: chefbook_test
          NODE_ENV: test
          SENTRY_SAMPLE_RATE: 0
          POSTGRES_DB: chefbook_test
          POSTGRES_USER: chefbook
          POSTGRES_PASSWORD: admin
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
          POSTGRES_SSL: false
          POSTGRES_LOGGING: false
          DATABASE_URL: postgresql://chefbook:admin@localhost:5432/chefbook_test?connection_limit=5&sslmode=disable
          SEARCH_PROVIDER: none
          STORAGE_TYPE: filesystem
          FILESYSTEM_STORAGE_PATH: ~/project/rsdata
          JOB_QUEUE_REDIS_HOST: localhost
          GRIP_URL: http://localhost:5561/
          GRIP_KEY: changeme
          FONTS_PATH: fonts
          EXPRESS_VIEWS_PATH: packages/backend/src/views
          FRONTEND_I18N_PATH: packages/frontend/src/assets/i18n
          JOB_QUEUE_WORKER_PATH: dist/apps/queue-worker/worker.cjs
      - image: postgres:16.1
        environment:
          POSTGRES_USER: chefbook
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: chefbook_test
      - image: valkey/valkey
    steps:
      - checkout
      - install-dependencies
      - run:
          name: prettier
          command: npx prettier --check .
      - run:
          name: lint, typecheck, build
          command: |
            APP_VERSION=${CIRCLE_TAG:-stg} \
            SENTRY_RELEASE=$CIRCLE_TAG \
            SOURCEMAP_UPLOAD=${CIRCLE_TAG:+true} \
            NX_SKIP_NX_CACHE=${CIRCLE_TAG:+true} \
            npx nx run-many --targets=build,lint,typecheck --output-style=static
          environment:
            ENVIRONMENT: production
      - run:
          name: migrate
          command: npx prisma migrate dev
      - run:
          name: start api
          command: node dist/apps/backend/main.cjs
          background: true
      - run:
          name: start queue-worker
          command: PORT=3001 node dist/apps/queue-worker/main.cjs
          background: true
      - run:
          name: wait for api
          command: dockerize -wait tcp://localhost:3000 -timeout 30s
      - run:
          name: wait for queue-worker
          command: dockerize -wait tcp://localhost:3001 -timeout 30s
      - run:
          name: test
          command: npx nx run-many --targets=test --output-style=static
          environment:
            APP_VERSION: ci
  push_backend:
    resource_class: large
    docker:
      - image: cimg/node:24.13
    steps:
      - checkout
      - setup_remote_docker:
          version: docker24
          docker_layer_caching: true
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: build and push recipesage.com image
          command: |
            VERSION=${CIRCLE_TAG:=stg}
            docker build \
            --build-arg VERSION=$VERSION \
            --build-arg FRONTEND_BUILD_TARGET=build \
            -f production.Dockerfile \
            -t julianpoy/recipesage:$VERSION \
            .

            docker push julianpoy/recipesage:$VERSION
  push_selfhost_amd64:
    resource_class: large
    docker:
      - image: cimg/node:24.13
    steps:
      - checkout
      - setup_remote_docker:
          version: docker24
          docker_layer_caching: true
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: build and push selfhost amd64
          command: |
            docker buildx build . \
              --push \
              --platform linux/amd64 \
              -f production.Dockerfile \
              --build-arg VERSION=${CIRCLE_TAG:=stg} \
              --build-arg FRONTEND_BUILD_TARGET=build:selfhost \
              -t julianpoy/recipesage-selfhost:${CIRCLE_TAG:=stg}-amd64
  push_selfhost_arm64:
    resource_class: arm.large
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: build and push selfhost arm64
          command: |
            docker buildx build . \
              --push \
              --platform linux/arm64/v8 \
              -f production.Dockerfile \
              --build-arg VERSION=${CIRCLE_TAG:=stg} \
              --build-arg FRONTEND_BUILD_TARGET=build:selfhost \
              -t julianpoy/recipesage-selfhost:${CIRCLE_TAG:=stg}-arm64
  push_selfhost_manifest:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: create and push selfhost merged image
          command: |
            docker buildx imagetools create -t julianpoy/recipesage-selfhost:${CIRCLE_TAG:=stg} \
              julianpoy/recipesage-selfhost:${CIRCLE_TAG:=stg}-amd64 \
              julianpoy/recipesage-selfhost:${CIRCLE_TAG:=stg}-arm64
  upload_static:
    resource_class: large
    docker:
      - image: cimg/node:24.13
    steps:
      - checkout
      - aws-cli/setup
      - install-dependencies
      - run:
          name: build-frontend
          command: (export APP_VERSION=${CIRCLE_TAG:=stg} && npx nx build frontend --skip-nx-cache)
          environment:
            ENVIRONMENT: production
      - run:
          name: move-frontend-build
          command: mv packages/frontend/www ./www
      - run:
          name: webapp-hosted.sh
          command: |
            APP_VERSION=${CIRCLE_TAG:=stg}
            BUCKET="s3://chefbook-static/frontend/$APP_VERSION/"

            find www/browser/ -type f -name "*.map" -delete

            aws s3 sync www/browser "$BUCKET" \
              --exclude "*" \
              --include "chunk-????????.*" \
              --include "main-????????.*" \
              --include "polyfills-????????.*" \
              --include "styles-????????.*" \
              --include "media/*-????????.*" \
              --acl public-read \
              --cache-control "public, max-age=2592000, immutable"

            aws s3 sync www/browser "$BUCKET" \
              --exclude "*" \
              --include "index.html" \
              --include "index.csr.html" \
              --include "service-worker.js" \
              --include "*/index.html" \
              --acl public-read \
              --cache-control "public, max-age=3600, must-revalidate"

            aws s3 sync www/browser "$BUCKET" \
              --exclude "chunk-????????.*" \
              --exclude "main-????????.*" \
              --exclude "polyfills-????????.*" \
              --exclude "styles-????????.*" \
              --exclude "media/*-????????.*" \
              --exclude "index.html" \
              --exclude "index.csr.html" \
              --exclude "service-worker.js" \
              --exclude "*/index.html" \
              --acl public-read \
              --cache-control "public, max-age=604800, must-revalidate"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - push_backend:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/
      - push_selfhost_amd64:
          requires:
            - build_and_test
          filters:
            tags:
              # We do not publish -beta versions for selfhost
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - push_selfhost_arm64:
          requires:
            - build_and_test
          filters:
            tags:
              # We do not publish -beta versions for selfhost
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - push_selfhost_manifest:
          requires:
            - push_selfhost_amd64
            - push_selfhost_arm64
          filters:
            tags:
              # We do not publish -beta versions for selfhost
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - upload_static:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/
