version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
commands:
  install-dependencies:
    steps:
      # - restore_cache:
      #     keys:
      #       - dependency-cache-v3-{{ checksum "pnpm-lock.yaml" }}
      #       - dependency-cache-v3-
      - run:
          name: enable-corepack
          command: sudo corepack enable
      - run:
          name: install-deps
          command: "pnpm install --frozen-lockfile"
      # - save_cache:
      #     key: dependency-cache-v3-{{ checksum "pnpm-lock.yaml" }}
      #     paths:
      #       - ./node_modules
      #       - ~/.local/share/pnpm/store
jobs:
  build_and_test:
    resource_class: large
    docker:
      - image: cimg/node:24.13
        environment:
          RS_TEST_DB_USERNAME: chefbook
          RS_TEST_DB_PASSWORD: admin
          RS_TEST_DB_DATABASE: chefbook_test
          NODE_ENV: test
          SENTRY_SAMPLE_RATE: 0
          POSTGRES_DB: chefbook_test
          POSTGRES_USER: chefbook
          POSTGRES_PASSWORD: admin
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
          POSTGRES_SSL: false
          POSTGRES_LOGGING: false
          DATABASE_URL: postgresql://chefbook:admin@localhost:5432/chefbook_test?connection_limit=5&sslmode=disable
          SEARCH_PROVIDER: none
          STORAGE_TYPE: filesystem
          FILESYSTEM_STORAGE_PATH: ~/project/rsdata
          JOB_QUEUE_REDIS_HOST: localhost
          GRIP_URL: http://localhost:5561/
          GRIP_KEY: changeme
          FONTS_PATH: fonts
          EXPRESS_VIEWS_PATH: packages/backend/src/views
          FRONTEND_I18N_PATH: packages/frontend/src/assets/i18n
          JOB_QUEUE_WORKER_PATH: dist/apps/queue-worker/worker.cjs
      - image: postgres:16.1
        environment:
          POSTGRES_USER: chefbook
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: chefbook_test
      - image: valkey/valkey
    steps:
      - checkout
      - install-dependencies
      - run:
          name: install-pandoc
          command: sudo apt-get update && sudo apt-get install -y pandoc
      - run:
          name: prettier
          command: pnpm exec prettier --check .
      - run:
          name: lint, typecheck, build
          command: |
            APP_VERSION=${CIRCLE_TAG:-stg} \
            SENTRY_RELEASE=$CIRCLE_TAG \
            SOURCEMAP_UPLOAD=${CIRCLE_TAG:+true} \
            NX_SKIP_NX_CACHE=${CIRCLE_TAG:+true} \
            pnpm exec nx run-many --targets=build,lint,typecheck --output-style=static
          environment:
            ENVIRONMENT: production
            NODE_OPTIONS: --max-old-space-size=4096
      - run:
          name: migrate
          command: pnpm exec prisma migrate dev
      - run:
          name: start api
          command: node dist/apps/backend/main.cjs
          background: true
      - run:
          name: start queue-worker
          command: PORT=3001 node dist/apps/queue-worker/main.cjs
          background: true
      - run:
          name: wait for api
          command: dockerize -wait tcp://localhost:3000 -timeout 30s
      - run:
          name: wait for queue-worker
          command: dockerize -wait tcp://localhost:3001 -timeout 30s
      - run:
          name: test
          command: pnpm exec nx run-many --targets=test --output-style=static
          environment:
            APP_VERSION: ci
  push_backend:
    resource_class: large
    docker:
      - image: cimg/node:24.13
    steps:
      - checkout
      - setup_remote_docker:
          version: docker24
          docker_layer_caching: true
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: build and push api
          command: |
            TAG=${CIRCLE_TAG:-stg}
            docker build --build-arg VERSION=$TAG -f production.Dockerfile -t julianpoy/recipesage:api-$TAG .
            docker push julianpoy/recipesage:api-$TAG
  push_backend_selfhost_amd64:
    resource_class: large
    docker:
      - image: cimg/node:24.13
    steps:
      - checkout
      - setup_remote_docker:
          version: docker24
          docker_layer_caching: true
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: build and push api amd64
          command: |
            docker buildx build . \
              --push \
              --platform linux/amd64 \
              -f production.Dockerfile \
              --build-arg VERSION=${CIRCLE_TAG:=stg} \
              -t julianpoy/recipesage-selfhost:api-${CIRCLE_TAG:=stg}-amd64
  push_backend_selfhost_arm64:
    resource_class: arm.large
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: build and push api arm64
          command: |
            docker buildx build . \
              --push \
              --platform linux/arm64/v8 \
              -f production.Dockerfile \
              --build-arg VERSION=${CIRCLE_TAG:=stg} \
              -t julianpoy/recipesage-selfhost:api-${CIRCLE_TAG:=stg}-arm64
  push_backend_selfhost_manifest:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: create and push api manifest
          command: |
            docker buildx imagetools create -t julianpoy/recipesage-selfhost:api-${CIRCLE_TAG:=stg} \
              julianpoy/recipesage-selfhost:api-${CIRCLE_TAG:=stg}-amd64 \
              julianpoy/recipesage-selfhost:api-${CIRCLE_TAG:=stg}-arm64
  push_frontend:
    resource_class: large
    docker:
      - image: cimg/node:24.13
    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker:
          version: docker24
          docker_layer_caching: true
      - install-dependencies
      - run:
          name: build-frontend
          command: (export APP_VERSION=${CIRCLE_TAG:=stg} && pnpm exec nx build frontend --skip-nx-cache)
          environment:
            ENVIRONMENT: production
            NODE_OPTIONS: --max-old-space-size=4096
      - run:
          name: move-frontend-build
          command: mv packages/frontend/www ./www
      - run:
          name: set-frontend-version
          command: sed -i "s/window.version = \"development\";/window.version = \"${CIRCLE_TAG:=stg}\";/" www/index.html
      - run:
          name: upload frontend to s3
          command: |
            TAG=${CIRCLE_TAG:-stg}
            mkdir -p www-revhashed
            find www/ -regextype egrep -regex '.+\.[a-f0-9]{20}\..+' -exec mv -t www-revhashed/ -- {} +

            aws s3 sync www s3://chefbook-static/frontend/$TAG/ \
              --exclude "*" \
              --include "index.html" \
              --include "service-worker.js" \
              --acl public-read \
              --cache-control "public, max-age=3600, must-revalidate"

            aws s3 sync www s3://chefbook-static/frontend/$TAG/ \
              --exclude "index.html" \
              --exclude "service-worker.js" \
              --acl public-read \
              --cache-control "public, max-age=604800, must-revalidate"

            aws s3 sync www-revhashed s3://chefbook-static/frontend/$TAG/ \
              --acl public-read \
              --cache-control "public, max-age=2592000, immutable"
  push_www:
    resource_class: large
    docker:
      - image: cimg/node:24.13
    steps:
      - checkout
      - aws-cli/setup
      - install-dependencies
      - run:
          name: build-www
          command: (export APP_VERSION=${CIRCLE_TAG:=stg} && pnpm exec nx build www --skip-nx-cache)
          environment:
            ENVIRONMENT: production
      - run:
          name: move-www-build
          command: mv packages/www/dist ./www-dist
      - run:
          name: upload www to s3
          command: |
            TAG=${CIRCLE_TAG:-stg}

            aws s3 sync www-dist s3://chefbook-static/www/$TAG/ \
              --exclude "_astro/*" \
              --acl public-read \
              --cache-control "public, max-age=3600, must-revalidate"

            if [ -d www-dist/_astro ]; then
              aws s3 sync www-dist/_astro s3://chefbook-static/www/$TAG/_astro/ \
                --acl public-read \
                --cache-control "public, max-age=2592000, immutable"
            fi
  build_frontend_selfhost:
    resource_class: large
    docker:
      - image: cimg/node:24.13
    steps:
      - checkout
      - install-dependencies
      - run:
          name: build-frontend
          command: (export APP_VERSION=${CIRCLE_TAG:=stg} && pnpm exec nx build:selfhost frontend --skip-nx-cache)
          environment:
            ENVIRONMENT: production
            NODE_OPTIONS: --max-old-space-size=4096
      - run:
          name: move-frontend-build
          command: mv packages/frontend/www ./www
      - run:
          name: set-frontend-version
          command: sed -i "s/window.version = \"development\";/window.version = \"${CIRCLE_TAG:=stg}\";/" www/index.html
      - persist_to_workspace:
          root: .
          paths:
            - www
  push_frontend_selfhost_amd64:
    resource_class: large
    docker:
      - image: cimg/node:24.13
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: docker24
          docker_layer_caching: true
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: build and push static amd64
          command: |
            docker buildx build . \
              --push \
              --platform linux/amd64 \
              -f packages/frontend/selfhost.Dockerfile \
              --build-arg VERSION=${CIRCLE_TAG:=stg} \
              -t julianpoy/recipesage-selfhost:static-${CIRCLE_TAG:=stg}-amd64
  push_frontend_selfhost_arm64:
    resource_class: arm.large
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: build and push static arm64
          command: |
            docker buildx build . \
              --push \
              --platform linux/arm64/v8 \
              -f packages/frontend/selfhost.Dockerfile \
              --build-arg VERSION=${CIRCLE_TAG:=stg} \
              -t julianpoy/recipesage-selfhost:static-${CIRCLE_TAG:=stg}-arm64
  push_frontend_selfhost_manifest:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: create and push static manifest
          command: |
            docker buildx imagetools create -t julianpoy/recipesage-selfhost:static-${CIRCLE_TAG:=stg} \
              julianpoy/recipesage-selfhost:static-${CIRCLE_TAG:=stg}-amd64 \
              julianpoy/recipesage-selfhost:static-${CIRCLE_TAG:=stg}-arm64

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - push_backend:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/
      - push_backend_selfhost_amd64:
          requires:
            - build_and_test
          filters:
            tags:
              # We do not publish -beta versions for selfhost
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - push_backend_selfhost_arm64:
          requires:
            - build_and_test
          filters:
            tags:
              # We do not publish -beta versions for selfhost
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - push_backend_selfhost_manifest:
          requires:
            - push_backend_selfhost_amd64
            - push_backend_selfhost_arm64
          filters:
            tags:
              # We do not publish -beta versions for selfhost
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - push_frontend:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/
      - push_www:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/
      - build_frontend_selfhost:
          requires:
            - build_and_test
          filters:
            tags:
              # We do not publish -beta versions for selfhost
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - push_frontend_selfhost_amd64:
          requires:
            - build_frontend_selfhost
          filters:
            tags:
              # We do not publish -beta versions for selfhost
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - push_frontend_selfhost_arm64:
          requires:
            - build_frontend_selfhost
          filters:
            tags:
              # We do not publish -beta versions for selfhost
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - push_frontend_selfhost_manifest:
          requires:
            - push_frontend_selfhost_amd64
            - push_frontend_selfhost_arm64
          filters:
            tags:
              # We do not publish -beta versions for selfhost
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
