import { addIcons, setAssetPath } from "ionicons";
import {
  add,
  archive,
  arrowBack,
  arrowForward,
  arrowUndo,
  ban,
  banOutline,
  body,
  book,
  bookmarks,
  brush,
  bug,
  calendar,
  camera,
  card,
  caretBack,
  caretDown,
  caretDownSharp,
  caretForward,
  caretUp,
  cart,
  chatbox,
  chatboxEllipses,
  chatbubbles,
  checkbox,
  checkmark,
  chevronDown,
  chevronUp,
  close,
  closeCircle,
  cloudDownload,
  cloudUpload,
  code,
  codeWorking,
  compass,
  copy,
  create,
  cut,
  cutOutline,
  document,
  documentText,
  documentTextOutline,
  download,
  ellipsisVertical,
  eye,
  eyeOff,
  fileTrayFull,
  fitness,
  flashlight,
  folder,
  folderOpen,
  funnel,
  gitNetwork,
  heart,
  help,
  helpBuoy,
  home,
  homeOutline,
  image,
  images,
  informationCircle,
  key,
  language,
  languageOutline,
  laptop,
  leaf,
  link,
  list,
  logIn,
  logOut,
  logoFacebook,
  logoGithub,
  logoInstagram,
  logoPinterest,
  logoTwitter,
  mail,
  mailOpen,
  nutrition,
  open,
  options,
  pencil,
  people,
  person,
  personCircle,
  phonePortrait,
  pin,
  pricetag,
  pricetags,
  print,
  refresh,
  reload,
  removeCircle,
  reorderThree,
  resize,
  save,
  scale,
  search,
  send,
  server,
  settings,
  share,
  shareOutline,
  shareSocial,
  star,
  starOutline,
  statsChart,
  sunny,
  swapHorizontal,
  sync,
  tabletLandscape,
  text,
  textOutline,
  trash,
  trashBin,
  warning,
} from "ionicons/icons";

if (typeof window !== "undefined") {
  setAssetPath(window.location.origin + "/svg/");
}

addIcons({
  add,
  archive,
  "arrow-back": arrowBack,
  "arrow-forward": arrowForward,
  "arrow-undo": arrowUndo,
  ban,
  "ban-outline": banOutline,
  body,
  book,
  bookmarks,
  brush,
  bug,
  calendar,
  camera,
  card,
  "caret-back": caretBack,
  "caret-down": caretDown,
  "caret-down-sharp": caretDownSharp,
  "caret-forward": caretForward,
  "caret-up": caretUp,
  cart,
  chatbox,
  "chatbox-ellipses": chatboxEllipses,
  chatbubbles,
  checkbox,
  checkmark,
  "chevron-down": chevronDown,
  "chevron-up": chevronUp,
  close,
  "close-circle": closeCircle,
  "cloud-download": cloudDownload,
  "cloud-upload": cloudUpload,
  code,
  "code-working": codeWorking,
  compass,
  copy,
  create,
  cut,
  "cut-outline": cutOutline,
  document,
  "document-text": documentText,
  "document-text-outline": documentTextOutline,
  download,
  "ellipsis-vertical": ellipsisVertical,
  eye,
  "eye-off": eyeOff,
  "file-tray-full": fileTrayFull,
  fitness,
  flashlight,
  folder,
  "folder-open": folderOpen,
  funnel,
  "git-network": gitNetwork,
  heart,
  help,
  "help-buoy": helpBuoy,
  home,
  "home-outline": homeOutline,
  image,
  images,
  "information-circle": informationCircle,
  key,
  language,
  "language-outline": languageOutline,
  laptop,
  leaf,
  link,
  list,
  "log-in": logIn,
  "log-out": logOut,
  "logo-facebook": logoFacebook,
  "logo-github": logoGithub,
  "logo-instagram": logoInstagram,
  "logo-pinterest": logoPinterest,
  "logo-twitter": logoTwitter,
  mail,
  "mail-open": mailOpen,
  nutrition,
  open,
  options,
  pencil,
  people,
  person,
  "person-circle": personCircle,
  "phone-portrait": phonePortrait,
  pin,
  pricetag,
  pricetags,
  print,
  refresh,
  reload,
  "remove-circle": removeCircle,
  "reorder-three": reorderThree,
  resize,
  save,
  scale,
  search,
  send,
  server,
  settings,
  share,
  "share-outline": shareOutline,
  "share-social": shareSocial,
  star,
  "star-outline": starOutline,
  "stats-chart": statsChart,
  sunny,
  "swap-horizontal": swapHorizontal,
  sync,
  "tablet-landscape": tabletLandscape,
  text,
  "text-outline": textOutline,
  trash,
  "trash-bin": trashBin,
  warning,
});
