import {
  AppPreferenceTypes,
  AppTheme,
  MealPlanStartOfWeekOptions,
  MealPlanViewTypeOptions,
  MyRecipesIncludeFriendsOptions,
  MyRecipesSortOptions,
  MyRecipesViewTypeOptions,
  PreferencesSync,
  ShoppingListSortOptions,
  StartPageOptions,
  SupportedFontSize,
  SupportedLanguages,
} from "@recipesage/util/shared";

export function preferencesFactory(): AppPreferenceTypes {
  return {
    preferencesVersion: 1,
    "global.enableSplitPane": true,
    "global.language": SupportedLanguages.EN_US,
    "global.fontSize": SupportedFontSize.X1_0,
    "global.theme": AppTheme.Default,
    "global.preferencesSync": PreferencesSync.Enabled,
    "global.startPage": StartPageOptions.MyRecipes,
    "myRecipes.enableLabelIntersection": false,
    "myRecipes.showLabels": true,
    "myRecipes.showLabelChips": false,
    "myRecipes.showImages": true,
    "myRecipes.showSource": false,
    "myRecipes.showRecipeDescription": true,
    "myRecipes.viewType": MyRecipesViewTypeOptions.Tiles,
    "myRecipes.sortBy": MyRecipesSortOptions.CreatedAtDesc,
    "myRecipes.includeFriends": MyRecipesIncludeFriendsOptions.No,
    "recipeDetails.enableWakeLock": true,
    "recipeDetails.autoExpandNutrition": false,
    "cookMode.fontSize": SupportedFontSize.PX20,
    "manageLabels.showCreatedAt": false,
    "measurementConverter.showFractions": true,
    "MealPlan.showAddedBy": true,
    "MealPlan.showAddedOn": true,
    "MealPlan.startOfWeek": MealPlanStartOfWeekOptions.Monday,
    "MealPlan.viewType": MealPlanViewTypeOptions.Calendar,
    "ShoppingList.sortBy": ShoppingListSortOptions.CreatedAtDesc,
    "ShoppingList.showAddedBy": true,
    "ShoppingList.showAddedOn": true,
    "ShoppingList.showRecipeTitle": true,
    "ShoppingList.preferDelete": false,
    "ShoppingList.groupSimilar": true,
    "ShoppingList.groupCategories": true,
    "ShoppingList.ignoreItemTitles": "",
  };
}
