export const UPSERT_SHOPPING_LIST_ITEMS_PAGINATION_LIMIT = 100;
export const UPDATE_SHOPPING_LIST_ITEMS_PAGINATION_LIMIT = 100;
export const DELETE_SHOPPING_LIST_ITEMS_PAGINATION_LIMIT = 1000;
export const CREATE_SHOPPING_LIST_ITEMS_PAGINATION_LIMIT = 1000;
export const SHOPPING_LIST_TITLE_LENGTH_LIMIT = 254;
export const SHOPPING_LIST_ITEMS_TITLE_LENGTH_LIMIT = 254;
export const SHOPPING_LIST_CATEGORY_ORDER_LENGTH_LIMIT = 10000;

export const UPSERT_MEAL_PLAN_ITEMS_PAGINATION_LIMIT = 100;
export const UPDATE_MEAL_PLAN_ITEMS_PAGINATION_LIMIT = 100;
export const DELETE_MEAL_PLAN_ITEMS_PAGINATION_LIMIT = 1000;
export const CREATE_MEAL_PLAN_ITEMS_PAGINATION_LIMIT = 1000;
export const MEAL_PLAN_TITLE_LENGTH_LIMIT = 254;
export const MEAL_PLAN_ITEMS_TITLE_LENGTH_LIMIT = 254;
export const MEAL_PLAN_ITEMS_MEAL_LENGTH_LIMIT = 254;
export const MEAL_PLAN_ITEMS_NOTES_LENGTH_LIMIT = 10000;
export const MEAL_PLAN_CUSTOM_MEAL_OPTIONS_LENGTH_LIMIT = 10000;

export const SEARCH_RECIPES_BY_INGREDIENTS_MAX_TERMS = 30;
export const SEARCH_RECIPES_BY_INGREDIENTS_MAX_TERM_LENGTH = 255;
