export type CookingTemperatureCategory =
  | "poultry"
  | "redMeatPork"
  | "seafood"
  | "eggs"
  | "sugarCandy"
  | "chocolate"
  | "other"
  | "oilSmokePoints";

export type TemperatureKind = "oil" | "smokePoint";

export interface CookingTemperatureEntry {
  key: string;
  category: CookingTemperatureCategory;
  fahrenheit?: number;
  fahrenheitRange?: [number, number];
  restMinutes?: number;
  isSafetyMinimum: boolean;
  isDangerZone?: boolean;
  visualCueOnly?: boolean;
  tempKind?: TemperatureKind;
  searchAliases?: string[];
}

export const COOKING_TEMPERATURE_CATEGORIES: CookingTemperatureCategory[] = [
  "poultry",
  "redMeatPork",
  "seafood",
  "eggs",
  "sugarCandy",
  "chocolate",
  "other",
  "oilSmokePoints",
];

export const COOKING_TEMPERATURES: CookingTemperatureEntry[] = [
  {
    key: "poultryAll",
    category: "poultry",
    fahrenheit: 165,
    isSafetyMinimum: true,
    searchAliases: [
      "bird",
      "drumstick",
      "thigh",
      "breast",
      "wing",
      "fowl",
      "game",
    ],
  },
  {
    key: "groundPoultry",
    category: "poultry",
    fahrenheit: 165,
    isSafetyMinimum: true,
    searchAliases: [
      "mince",
      "burger",
      "turkey burger",
      "chicken burger",
      "meatball",
      "sausage",
      "patty",
    ],
  },
  {
    key: "stuffing",
    category: "poultry",
    fahrenheit: 165,
    isSafetyMinimum: true,
    searchAliases: ["dressing", "filling"],
  },
  {
    key: "poultryDarkMeatPreference",
    category: "poultry",
    fahrenheit: 175,
    isSafetyMinimum: false,
    searchAliases: ["thigh", "leg", "drumstick"],
  },
  {
    key: "fryChicken",
    category: "poultry",
    fahrenheit: 350,
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: ["drumstick", "thigh", "breast", "oil", "deep fry"],
  },
  {
    key: "fryChickenWings",
    category: "poultry",
    fahrenheit: 375,
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: ["buffalo", "oil", "deep fry"],
  },
  {
    key: "fryChickenTenders",
    category: "poultry",
    fahrenheit: 350,
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: ["strips", "fingers", "nuggets", "oil", "deep fry"],
  },

  {
    key: "beefBlueRare",
    category: "redMeatPork",
    fahrenheit: 115,
    isSafetyMinimum: false,
    searchAliases: ["steak", "bleu"],
  },
  {
    key: "beefRare",
    category: "redMeatPork",
    fahrenheit: 125,
    isSafetyMinimum: false,
    searchAliases: ["steak"],
  },
  {
    key: "beefMediumRare",
    category: "redMeatPork",
    fahrenheit: 132,
    isSafetyMinimum: false,
    searchAliases: ["steak", "med rare"],
  },
  {
    key: "beefWhole",
    category: "redMeatPork",
    fahrenheit: 145,
    restMinutes: 3,
    isSafetyMinimum: true,
    searchAliases: [
      "steak",
      "roast",
      "chop",
      "ribeye",
      "sirloin",
      "tenderloin",
      "filet",
      "medium",
    ],
  },
  {
    key: "beefMediumWell",
    category: "redMeatPork",
    fahrenheit: 152,
    isSafetyMinimum: false,
    searchAliases: ["steak"],
  },
  {
    key: "beefWellDone",
    category: "redMeatPork",
    fahrenheit: 160,
    isSafetyMinimum: false,
    searchAliases: ["steak"],
  },
  {
    key: "groundBeef",
    category: "redMeatPork",
    fahrenheit: 160,
    isSafetyMinimum: true,
    searchAliases: [
      "burger",
      "hamburger",
      "meatball",
      "meatloaf",
      "mince",
      "patty",
    ],
  },
  {
    key: "brisketSlice",
    category: "redMeatPork",
    fahrenheitRange: [200, 205],
    isSafetyMinimum: false,
    searchAliases: ["beef", "bbq", "smoke", "point", "flat"],
  },
  {
    key: "beefShortRibs",
    category: "redMeatPork",
    fahrenheit: 203,
    isSafetyMinimum: false,
    searchAliases: ["bbq", "smoke", "plate", "dino"],
  },
  {
    key: "beefBraising",
    category: "redMeatPork",
    fahrenheitRange: [200, 205],
    isSafetyMinimum: false,
    searchAliases: [
      "pot roast",
      "chuck",
      "stew",
      "braise",
      "braised",
      "shred",
      "fork tender",
    ],
  },

  {
    key: "porkWhole",
    category: "redMeatPork",
    fahrenheit: 145,
    restMinutes: 3,
    isSafetyMinimum: true,
    searchAliases: [
      "chop",
      "roast",
      "tenderloin",
      "loin",
      "fresh ham",
      "medium",
    ],
  },
  {
    key: "porkWellDone",
    category: "redMeatPork",
    fahrenheit: 160,
    isSafetyMinimum: false,
    searchAliases: ["chop", "tenderloin", "loin"],
  },
  {
    key: "groundPork",
    category: "redMeatPork",
    fahrenheit: 160,
    isSafetyMinimum: true,
    searchAliases: ["sausage", "mince", "meatball"],
  },
  {
    key: "hamPrecookedReheat",
    category: "redMeatPork",
    fahrenheit: 165,
    isSafetyMinimum: true,
    searchAliases: ["leftover"],
  },
  {
    key: "pulledPork",
    category: "redMeatPork",
    fahrenheit: 203,
    isSafetyMinimum: false,
    searchAliases: ["boston butt", "pork shoulder", "bbq", "smoke"],
  },
  {
    key: "porkRibs",
    category: "redMeatPork",
    fahrenheitRange: [200, 205],
    isSafetyMinimum: false,
    searchAliases: ["baby back", "spare", "st louis", "bbq", "smoke"],
  },

  {
    key: "lambRare",
    category: "redMeatPork",
    fahrenheit: 125,
    isSafetyMinimum: false,
    searchAliases: ["chop", "rack"],
  },
  {
    key: "lambMediumRare",
    category: "redMeatPork",
    fahrenheit: 135,
    isSafetyMinimum: false,
    searchAliases: ["chop", "rack", "med rare"],
  },
  {
    key: "lambWhole",
    category: "redMeatPork",
    fahrenheit: 145,
    restMinutes: 3,
    isSafetyMinimum: true,
    searchAliases: ["chop", "rack", "leg", "roast", "medium"],
  },
  {
    key: "lambMediumWell",
    category: "redMeatPork",
    fahrenheit: 155,
    isSafetyMinimum: false,
    searchAliases: ["chop", "rack"],
  },
  {
    key: "lambWellDone",
    category: "redMeatPork",
    fahrenheit: 165,
    isSafetyMinimum: false,
    searchAliases: ["chop", "rack"],
  },
  {
    key: "groundLamb",
    category: "redMeatPork",
    fahrenheit: 160,
    isSafetyMinimum: true,
    searchAliases: ["mince", "meatball", "kofta", "merguez"],
  },

  {
    key: "vealWhole",
    category: "redMeatPork",
    fahrenheit: 145,
    restMinutes: 3,
    isSafetyMinimum: true,
    searchAliases: ["chop", "roast", "cutlet"],
  },
  {
    key: "groundVeal",
    category: "redMeatPork",
    fahrenheit: 160,
    isSafetyMinimum: true,
    searchAliases: ["mince", "meatball"],
  },

  {
    key: "finfish",
    category: "seafood",
    fahrenheit: 145,
    isSafetyMinimum: true,
    searchAliases: [
      "salmon",
      "tuna",
      "cod",
      "tilapia",
      "trout",
      "halibut",
      "snapper",
      "bass",
      "fillet",
      "filet",
    ],
  },
  {
    key: "salmonMediumRare",
    category: "seafood",
    fahrenheit: 125,
    isSafetyMinimum: false,
    searchAliases: ["fish", "med rare"],
  },
  {
    key: "salmonMedium",
    category: "seafood",
    fahrenheit: 130,
    isSafetyMinimum: false,
    searchAliases: ["fish"],
  },
  {
    key: "tunaRare",
    category: "seafood",
    fahrenheit: 110,
    isSafetyMinimum: false,
    searchAliases: ["fish", "ahi", "yellowfin", "bluefin", "seared"],
  },
  {
    key: "tunaMediumRare",
    category: "seafood",
    fahrenheit: 125,
    isSafetyMinimum: false,
    searchAliases: ["fish", "ahi", "yellowfin", "bluefin", "med rare"],
  },
  {
    key: "tunaMedium",
    category: "seafood",
    fahrenheit: 140,
    isSafetyMinimum: false,
    searchAliases: ["fish", "ahi", "yellowfin", "bluefin"],
  },
  {
    key: "shrimpLobsterCrab",
    category: "seafood",
    visualCueOnly: true,
    isSafetyMinimum: true,
    searchAliases: ["prawn", "crustacean"],
  },
  {
    key: "scallops",
    category: "seafood",
    visualCueOnly: true,
    isSafetyMinimum: true,
  },
  {
    key: "shellfish",
    category: "seafood",
    visualCueOnly: true,
    isSafetyMinimum: true,
    searchAliases: ["bivalve", "shellfish", "clam", "oyster", "mussel"],
  },
  {
    key: "fryFish",
    category: "seafood",
    fahrenheit: 365,
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: [
      "cod",
      "haddock",
      "fish and chips",
      "oil",
      "deep fry",
      "battered",
    ],
  },

  {
    key: "eggsFresh",
    category: "eggs",
    visualCueOnly: true,
    isSafetyMinimum: true,
    searchAliases: ["fried", "scrambled", "poached", "over easy", "sunny side"],
  },
  {
    key: "eggDishes",
    category: "eggs",
    fahrenheit: 160,
    isSafetyMinimum: true,
    searchAliases: ["quiche", "frittata", "custard", "casserole", "strata"],
  },
  {
    key: "custard",
    category: "eggs",
    fahrenheitRange: [180, 183],
    isSafetyMinimum: false,
    searchAliases: [
      "creme anglaise",
      "pastry cream",
      "patissiere",
      "curd",
      "lemon curd",
      "stirred",
    ],
  },

  {
    key: "sugarThread",
    category: "sugarCandy",
    fahrenheitRange: [230, 234],
    isSafetyMinimum: false,
    searchAliases: ["candy", "syrup", "glaze"],
  },
  {
    key: "sugarSoftBall",
    category: "sugarCandy",
    fahrenheitRange: [234, 240],
    isSafetyMinimum: false,
    searchAliases: ["candy", "fudge", "fondant", "buttercream"],
  },
  {
    key: "sugarFirmBall",
    category: "sugarCandy",
    fahrenheitRange: [244, 248],
    isSafetyMinimum: false,
    searchAliases: ["candy", "caramel", "marshmallow"],
  },
  {
    key: "sugarHardBall",
    category: "sugarCandy",
    fahrenheitRange: [250, 266],
    isSafetyMinimum: false,
    searchAliases: ["candy", "nougat", "marshmallow", "divinity"],
  },
  {
    key: "sugarSoftCrack",
    category: "sugarCandy",
    fahrenheitRange: [270, 290],
    isSafetyMinimum: false,
    searchAliases: ["candy", "taffy", "butterscotch"],
  },
  {
    key: "sugarHardCrack",
    category: "sugarCandy",
    fahrenheitRange: [300, 310],
    isSafetyMinimum: false,
    searchAliases: ["candy", "brittle", "toffee", "lollipop"],
  },
  {
    key: "sugarCaramel",
    category: "sugarCandy",
    fahrenheitRange: [320, 350],
    isSafetyMinimum: false,
    searchAliases: ["caramel", "burnt sugar", "amber"],
  },

  {
    key: "chocolateDarkMelt",
    category: "chocolate",
    fahrenheitRange: [120, 130],
    isSafetyMinimum: false,
    searchAliases: [
      "tempering",
      "couverture",
      "semisweet",
      "bittersweet",
      "melt",
    ],
  },
  {
    key: "chocolateDarkCool",
    category: "chocolate",
    fahrenheitRange: [82, 84],
    isSafetyMinimum: false,
    searchAliases: [
      "tempering",
      "couverture",
      "semisweet",
      "bittersweet",
      "cool",
      "seed",
    ],
  },
  {
    key: "chocolateDarkWork",
    category: "chocolate",
    fahrenheitRange: [88, 90],
    isSafetyMinimum: false,
    searchAliases: [
      "tempering",
      "couverture",
      "semisweet",
      "bittersweet",
      "working",
      "dipping",
    ],
  },
  {
    key: "chocolateMilkMelt",
    category: "chocolate",
    fahrenheitRange: [105, 115],
    isSafetyMinimum: false,
    searchAliases: ["tempering", "couverture", "melt"],
  },
  {
    key: "chocolateMilkCool",
    category: "chocolate",
    fahrenheitRange: [81, 82],
    isSafetyMinimum: false,
    searchAliases: ["tempering", "couverture", "cool", "seed"],
  },
  {
    key: "chocolateMilkWork",
    category: "chocolate",
    fahrenheitRange: [85, 87],
    isSafetyMinimum: false,
    searchAliases: ["tempering", "couverture", "working", "dipping"],
  },
  {
    key: "chocolateWhiteMelt",
    category: "chocolate",
    fahrenheitRange: [105, 115],
    isSafetyMinimum: false,
    searchAliases: ["tempering", "couverture", "melt"],
  },
  {
    key: "chocolateWhiteCool",
    category: "chocolate",
    fahrenheitRange: [79, 81],
    isSafetyMinimum: false,
    searchAliases: ["tempering", "couverture", "cool", "seed"],
  },
  {
    key: "chocolateWhiteWork",
    category: "chocolate",
    fahrenheitRange: [82, 84],
    isSafetyMinimum: false,
    searchAliases: ["tempering", "couverture", "working", "dipping"],
  },

  {
    key: "leftovers",
    category: "other",
    fahrenheit: 165,
    isSafetyMinimum: true,
    searchAliases: ["reheat", "reheating", "warm up", "casserole", "bake"],
  },
  {
    key: "hotHolding",
    category: "other",
    fahrenheit: 140,
    isSafetyMinimum: true,
    searchAliases: ["buffet", "warm", "chafer", "holding", "serve"],
  },
  {
    key: "dangerZone",
    category: "other",
    fahrenheitRange: [40, 140],
    isSafetyMinimum: false,
    isDangerZone: true,
    searchAliases: ["bacteria", "spoilage", "leftover", "warm"],
  },
  {
    key: "fryGeneral",
    category: "other",
    fahrenheitRange: [350, 375],
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: ["oil", "fryer", "deep fry"],
  },
  {
    key: "fryFrenchBlanch",
    category: "other",
    fahrenheit: 325,
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: ["chips", "potato", "fries"],
  },
  {
    key: "fryFrenchFinish",
    category: "other",
    fahrenheit: 375,
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: ["chips", "potato", "fries"],
  },
  {
    key: "fryDoughnuts",
    category: "other",
    fahrenheit: 370,
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: ["donut", "oil"],
  },
  {
    key: "fryTempura",
    category: "other",
    fahrenheit: 340,
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: ["japanese", "vegetables", "shrimp", "oil"],
  },
  {
    key: "fryOnionRings",
    category: "other",
    fahrenheit: 375,
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: ["onion", "oil"],
  },
  {
    key: "fryFritters",
    category: "other",
    fahrenheit: 360,
    isSafetyMinimum: false,
    tempKind: "oil",
    searchAliases: ["corn fritter", "beignet", "hush puppies", "oil"],
  },

  {
    key: "smokeAvocadoRefined",
    category: "oilSmokePoints",
    fahrenheit: 520,
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["avocado", "high heat", "searing", "stir fry", "wok"],
  },
  {
    key: "smokeGhee",
    category: "oilSmokePoints",
    fahrenheit: 485,
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["ghee", "clarified butter", "indian", "high heat"],
  },
  {
    key: "smokePeanut",
    category: "oilSmokePoints",
    fahrenheit: 450,
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["peanut", "groundnut", "deep fry", "wok"],
  },
  {
    key: "smokeSunflowerRefined",
    category: "oilSmokePoints",
    fahrenheit: 450,
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["sunflower", "high oleic"],
  },
  {
    key: "smokeOliveRefined",
    category: "oilSmokePoints",
    fahrenheitRange: [390, 465],
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["olive", "pure olive", "light olive", "refined olive"],
  },
  {
    key: "smokeGrapeseed",
    category: "oilSmokePoints",
    fahrenheit: 420,
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["grapeseed", "grape seed"],
  },
  {
    key: "smokeCanola",
    category: "oilSmokePoints",
    fahrenheit: 400,
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["canola", "rapeseed", "neutral"],
  },
  {
    key: "smokeVegetable",
    category: "oilSmokePoints",
    fahrenheit: 400,
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["vegetable oil", "soybean", "neutral oil"],
  },
  {
    key: "smokeCoconutRefined",
    category: "oilSmokePoints",
    fahrenheit: 400,
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["coconut", "refined coconut"],
  },
  {
    key: "smokeOliveExtraVirgin",
    category: "oilSmokePoints",
    fahrenheitRange: [350, 410],
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["evoo", "extra virgin", "olive"],
  },
  {
    key: "smokeSesameToasted",
    category: "oilSmokePoints",
    fahrenheit: 350,
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["sesame", "toasted sesame", "finishing", "asian"],
  },
  {
    key: "smokeCoconutVirgin",
    category: "oilSmokePoints",
    fahrenheit: 350,
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["coconut", "virgin coconut", "unrefined"],
  },
  {
    key: "smokeButter",
    category: "oilSmokePoints",
    fahrenheitRange: [300, 350],
    isSafetyMinimum: false,
    tempKind: "smokePoint",
    searchAliases: ["butter", "dairy"],
  },
];
